name: Check Wheel Contents

on:
  workflow_call:

jobs:
  check-wheel:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install check-wheel-contents

    - name: Build wheel
      run: |
        python setup.py sdist bdist_wheel

    - name: Check wheel contents
      run: |
        check-wheel-contents dist/*.whl
