name: Call Python package workflow

on:
  workflow_dispatch:

jobs:
  call-python-package:
    uses: ./.github/workflows/test.yml
    
  check-wheel:
    needs: [call-python-package]
    uses: ./.github/workflows/check-wheel.yml